name: gallery_app
description: A beautiful gallery app for browsing files from local server
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  permission_handler: ^10.4.5
  dio: ^5.3.4
  path_provider: ^2.1.2
  device_info_plus: ^9.1.2
  flutter_colorpicker: ^1.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
